#ifndef BANKRESULT_H
#define BANKRESULT_H

enum BankResult
{
    SUCCESS,
    ACCOUNT_NOT_FOUND,
    WRONG_PIN,
    INVALID_AMOUNT,
    INSUFFICIENT_BALANCE,
    RECEIVER_NOT_FOUND,
    SAME_ACCOUNT_TRANSFER
};

#endif